site_name: Fathom
site_url: http://fathom.gitblit.com
repo_url: https://github.com/gitblit/fathom
repo_name: 'GitHub'
site_description: A JVM-based Microservice Foundation
site_author: James Moger
copyright: (c) 2015 James Moger
theme: readthedocs
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - admonition
    - nl2br
    - def_list
pages:
  - 'index.md'
  - Getting Started:
      - Quickstart: 'quickstart.md'
  - Core:
      - About: 'about.md'
      - Layout: 'layout.md'
      - Configuration: 'configuration.md'
      - Services: 'services.md'
      - Modules: 'modules.md'
      - Components.java: 'components.md'
      - Servlets.java: 'servlets.md'
      - Fathom.java: 'fathom.md'
      - Logging: 'logging.md'
      - Deployment: 'deployment.md'
      - Maven Tricks: 'maven.md'
  - Modules:
      - 'Fathom-REST' : 'rest.md'
      - 'Fathom-Security' : 'security.md'
      - 'Fathom-REST-Security' : 'rest-security.md'
      - 'Fathom-REST-Shiro' : 'rest-shiro.md'
      - 'Fathom-REST-Swagger' : 'rest-swagger.md'
      - 'Fathom-Metrics' : 'metrics.md'
      - 'Fathom-Mailer' : 'mail.md'
      - 'Fathom-Eventbus' : 'eventbus.md'
      - 'Fathom-JCache' : 'jcache.md'
      - 'Fathom-Quartz' : 'quartz.md'
      - 'Fathom-Test-Tools' : 'testing.md'
