site_name: Fathom
site_url: http://fathom.gitblit.com
repo_url: https://github.com/gitblit/fathom
repo_name: 'GitHub'
site_description: A JVM-based Microservice Foundation
site_author: James Moger
copyright: (c) 2015 James Moger
theme: readthedocs
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
pages:
  - Fathom:
      - Introduction: 'index.md'
      - About: 'about.md'
      - Layout: 'layout.md'
      - Configuration: 'configuration.md'
      - Components: 'components.md'
      - Servlets: 'servlets.md'
      - Logging: 'logging.md'
      - Testing: 'testing.md'
      - Deployment: 'deployment.md'
  - Modules:
      - 'Fathom-REST' : 'rest.md'
      - 'Fathom-Security' : 'security.md'
      - 'Fathom-REST-Security' : 'rest-security.md'
      - 'Fathom-REST-Shiro' : 'rest-shiro.md'
      - 'Fathom-Metrics' : 'metrics.md'
      - 'Fathom-Mailer' : 'mail.md'
      - 'Fathom-Eventbus' : 'eventbus.md'
      - 'Fathom-JCache' : 'jcache.md'
      - 'Fathom-Quartz' : 'quartz.md'
